### ISSUE TITLE
Bug: Project alive?

### ISSUE THREAD

**Issue by leonardlin** [10xjs/locale-emoji#12]
localeEmoji('zh-Hant'); //

expected: TW
actual: CN

zh-Hant is split as code-Country

code: 'zh' is mapped to CN

I can make a PR to fix it, but it seems that PRs are not processed.
Any feedback?

**Comment by Kvintus** [comment]
> localeEmoji('zh-Hant'); //
> 
> expected: TW actual: CN
> 
> zh-Hant is split as code-Country
> 
> code: 'zh' is mapped to CN
> 
> I can make a PR to fix it, but it seems that PRs are not processed. Any feedback?

Hi, As the project really does seem to be dead. I made a complete rewrite in typescript and published at https://www.npmjs.com/package/locale2emoji 

Dont know if it's still any value to you if you want you can create the PR. There

**Comment by leonardlin** [comment]
@Kvintus amazing! I will open a PR there
